# Generated by Django 4.2.6 on 2023-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0002_alter_lottery_enddate_alter_lottery_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
