# Generated by Django 4.2.6 on 2023-10-23 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitty', '0005_alter_lotteryusermapping_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryusermapping',
            name='userName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='LotteryPayment',
            fields=[
                ('isActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('orderMonth', models.DateField()),
                ('paymentMode', models.CharField(choices=[('C', 'Cash'), ('O', 'Online')], max_length=1)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lotteryUserMappingId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitty.lotteryusermapping')),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
