# Generated by Django 4.2.6 on 2023-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0006_alter_lotteryusermapping_username_lotterypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryusermapping',
            name='gift',
            field=models.FloatField(default=0),
        ),
    ]
